file1=open("f1.txt","w")
file2=open("f2.txt","w")
file1.write("vandana")
file2.write("joshna")
file1.close()
file2.close()
file1=open("f1.txt","r")
file2=open("f2.txt","r")
a=file1.read()
b=file2.read()
print(a)
print(b)
file1=open("file1.txt","w")
file2=open("file2.txt","w")
file1=file1.write(b)
file2=file2.write(a)
file1.close()
file2.close()


